name: build ðŸ”¨

on:
    push:
        branches:
            - dev
    workflow_dispatch:

jobs:
    build:
        name: Build
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-12]
        runs-on: ${{ matrix.os }}
        steps:
            -
                name: Set up Go
                uses: actions/setup-go@v3
                with:
                    go-version:  '>=1.20'
            -
                name: Checkout the code
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            - 
                name: Go modules hygine
                run: |
                    go clean -modcache
                    go mod tidy
                working-directory: .
            -
                name: Build
                run: go build -v .
                working-directory: cmd/hqurlfind3r/